name: Deploy Frontend to EC2

on:
  push:
    branches:
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 400 key.pem
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Connect and run Docker on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i key.pem ubuntu@3.233.35.150 << 'EOF'
            cd /home/ubuntu/Front-end
            git pull origin QA
            docker build -t frontend-app .
            docker stop frontend-app || true
            docker rm frontend-app || true
            docker run -d -p 80:80 --name frontend-app --restart unless-stopped frontend-app
          EOF
