name: Deploy Frontend to EC2 # Workflow for QA Branch

on:
  push:
    branches:
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 400 key.pem
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Connect and run Docker on EC2
        run: |
          ssh -i key.pem ubuntu@3.233.35.150 << 'EOF'
            cd /home/ubuntu/tu-frontend               # <-- Aquí navegas al repo clonado en EC2
            git pull origin QA                        # <-- Actualizas el código desde GitHub
            docker build -t frontend-app .           # <-- Construyes la imagen localmente con el Dockerfile
            docker stop frontend-app || true          # <-- Detienes el contenedor actual si existe
            docker rm frontend-app || true            # <-- Lo eliminas para crear uno nuevo
            docker run -d -p 80:80 --name frontend-app --restart unless-stopped frontend-app   # <-- Corres el contenedor nuevo 
          EOF

