name: Build, Push to Docker Hub and Deploy to EC2

on:
  push:
    branches:
      - QA

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 2: Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Paso 3: login  Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Paso 4: build and upload Docker image
    - name: Build and push frontend Docker image
      run: |
        docker build -t alexmpz/frontend:qa ./  # Construir la imagen
        docker push alexmpz/frontend:qa  # Subir la imagen a Docker Hub

    # Paso 5: Cconection to the EC2 instance using elastic IP and deploy the containers
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}  # IP EC2 elastic
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          # Detener y eliminar contenedores antiguos si existen
          docker stop $(docker ps -aq)
          docker rm $(docker ps -aq)
          
          # Descargar la imagen del Docker Hub
          docker pull alexmpz/frontend:qa
          
          # Ejecutar el contenedor del frontend en el puerto 80
          docker run -d -p 80:80 alexmpz/frontend:qa
